#
# Common properties for notgen
#


spring:
  web:
    resources:
      # Add thumbnails directory to web server content path
      static-locations: classpath:/static,file:${se.terrassorkestern.notgen.storage.content}
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            analysis.configurer: se.terrassorkestern.notgen.index.AnalysisConfig
            directory.root: ./build/index
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  config:
    import: git.properties
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
        endpoint: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_STORAGE_ACCOUNT_NAME}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info

# Local storage config
se.terrassorkestern.notgen:
  ocr:
    enable: true
    songids: BF0D7BFF-8683-7B40-868E-155140E595F1
    username: ${OCR_USERNAME}
    license: ${OCR_LICENSE}
  storage:
    type: local
    input: /var/lib/notgen/input
    output: /var/lib/notgen/output
    content: /var/lib/notgen/static
    # Static content such as thumbnails and folders are stored here
