#
# Prod environment for AWS
#
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect

# Storage config
notgen:
  storage:
    type: s3
    input: to-scores-original
    output: to-scores-generated-prod
