#
# Prod environment for Azure
#
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        search:
          backend.directory.root: /var/lib/notgen/index

# Storage config
se.terrassorkestern.notgen:
  storage:
    type: azure
    input: scores
    output: scoreparts
    content: static      # Mounted from static container
